version: '3.8'

services:
  app:
    image: 'covid19-monitor:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=abcd2024
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/covid19m
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=abcd2024
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

    ports:
      - 8081:8081

  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=abcd2024
      - POSTGRES_DB=covid19m
    ports:
      - 5432:5432

  front:
    image: covid19dashbord
    build:
      context: front/covid19dashbord
    container_name: front
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=abcd2024
    ports:
      - 4200:4200